#!/bin/sh
. /home/clearly/dwm/scripts/sb-colors.sh

PREV_TOTAL=0
PREV_IDLE=0

cpu() {
    CPU=($(grep '^cpu ' /proc/stat))
    IDLE=${CPU[4]}
    TOTAL=0
    for VALUE in "${CPU[@]:1}"; do
        TOTAL=$((TOTAL + VALUE))
    done

    DIFF_IDLE=$((IDLE - PREV_IDLE))
    DIFF_TOTAL=$((TOTAL - PREV_TOTAL))
    DIFF_USAGE=$(( (1000*(DIFF_TOTAL - DIFF_IDLE)/DIFF_TOTAL + 5)/10 ))
    PREV_TOTAL=$TOTAL
    PREV_IDLE=$IDLE

    if [ "$DIFF_USAGE" -ge 80 ]; then
        COLOR="$CPU_COLOR_HIGH"
    elif [ "$DIFF_USAGE" -ge 50 ]; then
        COLOR="$CPU_COLOR_MED"
    else
        COLOR="$CPU_COLOR_LOW"
    fi

    printf "%s %s%%" "$COLOR" "$DIFF_USAGE"
}

cpu

